In [0]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.14.0


In [6]:
hello = tf.constant("Hello, Tensorflow")
print(hello)
print(type(hello))

Tensor("Const_2:0", shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>


In [7]:
num1 = tf.constant(10)
num2 = tf.constant(20)
num3 = tf.add(num1, num2)
print(num3)

Tensor("Add:0", shape=(), dtype=int32)


In [10]:
# 2행 3열의 텐서를 생성
tensor = tf.constant(-1.0, shape=[2,3])
print(tensor)

Tensor("Const_5:0", shape=(2, 3), dtype=float32)


## 그래프 실행

In [11]:
sess = tf.Session()
print(sess.run(hello))

b'Hello, Tensorflow'


In [12]:
print(sess.run(tensor))

[[-1. -1. -1.]
 [-1. -1. -1.]]


## 텐서 플로워의 자료형
* 플레이스 홀더 : 나중에 값을 입력 받기 위해 사용되는 매개변수 (parameter)
* shape(?,3) 두번째 차원 요소가 3이다. 앞의 차원은 나중에 지정

In [0]:
tensorX = tf.placeholder(tf.float32, [None, 2])

In [0]:
# X 에 넣을 데이터 초기화
x_data = [[1,1], [2,2]]

In [0]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [0]:
sess.run(tensorX, feed_dict={tensorX:x_data})
sess.close()

## 행렬 연산

In [21]:
tensorX = tf.placeholder(tf.float32, [None,2])

W = tf.Variable(tf.random_normal([2,2]))
b = tf.Variable(tf.random_normal([2,1]))

print(W)
print(b)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32_ref>
<tf.Variable 'Variable_1:0' shape=(2, 1) dtype=float32_ref>


In [28]:
y = tf.matmul(tensorX, W) + b
y

<tf.Tensor 'add_3:0' shape=(2, 2) dtype=float32>

In [40]:
### x_data, W, b, y 값 출력해보기
print("x_data : \n{}\n" .format(x_data))

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print("W : \n{}\n" .format(sess.run(W)))
print("b : \n{}\n" .format(sess.run(b)))
print("y : \n{}\n" .format(sess.run(y, feed_dict={tensorX:x_data})))

sess.close()

x_data : 
[[1, 1], [2, 2]]

W : 
[[-1.0999758   0.43269685]
 [ 0.46331868  0.40857834]]

b : 
[[0.4271179 ]
 [0.00793871]]

y : 
[[-0.2095392  1.2683932]
 [-1.2653755  1.6904892]]



# MNIST

In [0]:
import tensorflow as tf

In [42]:
mnist = tf.keras.datasets.mnist
print(mnist)

<module 'tensorflow.python.keras.api._v1.keras.datasets.mnist' from '/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/api/_v1/keras/datasets/mnist/__init__.py'>


In [43]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [44]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [45]:
y_train[0:3]

array([5, 0, 4], dtype=uint8)

In [46]:
x_train[0:3]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

In [0]:
# 값의 정규화
# Dropout, 값의 정규화(0~1)
x_train, x_test = x_train/255.0, x_test/255.0

## tf 신경망 만들기

In [49]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28,28)),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [0]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [52]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 8s 137us/sample - loss: 0.2210 - acc: 0.9350
Epoch 2/5
60000/60000 [==============================] - 8s 131us/sample - loss: 0.0960 - acc: 0.9707
Epoch 3/5
60000/60000 [==============================] - 8s 133us/sample - loss: 0.0668 - acc: 0.9788
Epoch 4/5
60000/60000 [==============================] - 8s 132us/sample - loss: 0.0531 - acc: 0.9823
Epoch 5/5
60000/60000 [==============================] - 8s 132us/sample - loss: 0.0434 - acc: 0.9858


In [53]:
model.evaluate(x_test, y_test)

10000/10000 [==============================] - 1s 54us/sample - loss: 0.0737 - acc: 0.9787


[0.07369576109007467, 0.9787]