# Sect5. Logistic (regression) classifier

In [4]:
import tensorflow as tf
from tqdm import tqdm_notebook

tf.set_random_seed(777)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [5]:
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in tqdm_notebook(range(10001)):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0 or step < 10 :
            print("Step : {} \t Cost : {}".format(step, cost_val))
            
    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})

Step : 0 	 Cost : 2.5744638442993164
Step : 1 	 Cost : 2.4988784790039062
Step : 2 	 Cost : 2.423949956893921
Step : 3 	 Cost : 2.3497419357299805
Step : 4 	 Cost : 2.2763173580169678
Step : 5 	 Cost : 2.2037479877471924
Step : 6 	 Cost : 2.1321117877960205
Step : 7 	 Cost : 2.061492919921875
Step : 8 	 Cost : 1.9919800758361816
Step : 9 	 Cost : 1.9236685037612915
Step : 200 	 Cost : 0.5877482295036316
Step : 400 	 Cost : 0.5653448104858398
Step : 600 	 Cost : 0.5443302392959595
Step : 800 	 Cost : 0.5244359970092773
Step : 1000 	 Cost : 0.5055162310600281
Step : 1200 	 Cost : 0.4874860346317291
Step : 1400 	 Cost : 0.47029173374176025
Step : 1600 	 Cost : 0.45389464497566223
Step : 1800 	 Cost : 0.4382634162902832
Step : 2000 	 Cost : 0.4233691990375519
Step : 2200 	 Cost : 0.4091843068599701
Step : 2400 	 Cost : 0.39568057656288147
Step : 2600 	 Cost : 0.3828296661376953
Step : 2800 	 Cost : 0.37060317397117615
Step : 3000 	 Cost : 0.35897207260131836
Step : 3200 	 Cost : 0.34790778

In [6]:
print("# Hypothesis: \n{h} \n\n# Correct (Y): \n{c} \n\n# Accuracy: {a}".format(
    h = h, c = c, a = a
))

# Hypothesis: 
[[0.03591657]
 [0.16531888]
 [0.3287507 ]
 [0.7706742 ]
 [0.93262756]
 [0.977866  ]] 

# Correct (Y): 
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 

# Accuracy: 1.0


In [12]:
a = tf.equal(3, 3)
b = tf.cast(a, dtype=tf.float32)

sess = tf.Session()
sess.run(b)

1.0

### Classifying diabetes
> 당뇨병 예측하는 실습 예제
* 예측값이 1이면 당뇨병 O
* 예측값이 0이면 당뇨병 X

In [13]:
import pandas as pd

df=pd.read_csv("./data/data-03-diabetes.csv", header=None)
df.head(10)

0         1         2         3         4         5         6  \
0 -0.294118  0.487437  0.180328 -0.292929  0.000000  0.001490 -0.531170   
1 -0.882353 -0.145729  0.081967 -0.414141  0.000000 -0.207153 -0.766866   
2 -0.058824  0.839196  0.049180  0.000000  0.000000 -0.305514 -0.492741   
3 -0.882353 -0.105528  0.081967 -0.535354 -0.777778 -0.162444 -0.923997   
4  0.000000  0.376884 -0.344262 -0.292929 -0.602837  0.284650  0.887276   
5 -0.411765  0.165829  0.213115  0.000000  0.000000 -0.236960 -0.894962   
6 -0.647059 -0.216080 -0.180328 -0.353535 -0.791962 -0.076006 -0.854825   
7  0.176471  0.155779  0.000000  0.000000  0.000000  0.052161 -0.952178   
8 -0.764706  0.979899  0.147541 -0.090909  0.283688 -0.090909 -0.931682   
9 -0.058824  0.256281  0.573770  0.000000  0.000000  0.000000 -0.868488   

          7  8  
0 -0.033333  0  
1 -0.666667  1  
2 -0.633333  0  
3  0.000000  1  
4 -0.600000  0  
5 -0.700000  1  
6 -0.833333  0  
7 -0.733333  1  
8  0.066667  0  
9  0.100000  0

In [15]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

xy = np.loadtxt('./data/data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(" x_data.shape : {x_shape} \n y_data.shape : {y_shape}".format(
        x_shape = x_data.shape, 
        y_shape = y_data.shape
    ))

X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X,W)+b)

cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*
                      tf.log(1-hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

 x_data.shape : (759, 8) 
 y_data.shape : (759, 1)


In [16]:
print(len(xy)) 
xy[:10]

759


array([[-0.294118  ,  0.487437  ,  0.180328  , -0.292929  ,  0.        ,
         0.00149028, -0.53117   , -0.0333333 ,  0.        ],
       [-0.882353  , -0.145729  ,  0.0819672 , -0.414141  ,  0.        ,
        -0.207153  , -0.766866  , -0.666667  ,  1.        ],
       [-0.0588235 ,  0.839196  ,  0.0491803 ,  0.        ,  0.        ,
        -0.305514  , -0.492741  , -0.633333  ,  0.        ],
       [-0.882353  , -0.105528  ,  0.0819672 , -0.535354  , -0.777778  ,
        -0.162444  , -0.923997  ,  0.        ,  1.        ],
       [ 0.        ,  0.376884  , -0.344262  , -0.292929  , -0.602837  ,
         0.28465   ,  0.887276  , -0.6       ,  0.        ],
       [-0.411765  ,  0.165829  ,  0.213115  ,  0.        ,  0.        ,
        -0.23696   , -0.894962  , -0.7       ,  1.        ],
       [-0.647059  , -0.21608   , -0.180328  , -0.353535  , -0.791962  ,
        -0.0760059 , -0.854825  , -0.833333  ,  0.        ],
       [ 0.176471  ,  0.155779  ,  0.        ,  0.        ,  0

In [17]:
print(len(x_data)) 
x_data[:10]

759


array([[-0.294118  ,  0.487437  ,  0.180328  , -0.292929  ,  0.        ,
         0.00149028, -0.53117   , -0.0333333 ],
       [-0.882353  , -0.145729  ,  0.0819672 , -0.414141  ,  0.        ,
        -0.207153  , -0.766866  , -0.666667  ],
       [-0.0588235 ,  0.839196  ,  0.0491803 ,  0.        ,  0.        ,
        -0.305514  , -0.492741  , -0.633333  ],
       [-0.882353  , -0.105528  ,  0.0819672 , -0.535354  , -0.777778  ,
        -0.162444  , -0.923997  ,  0.        ],
       [ 0.        ,  0.376884  , -0.344262  , -0.292929  , -0.602837  ,
         0.28465   ,  0.887276  , -0.6       ],
       [-0.411765  ,  0.165829  ,  0.213115  ,  0.        ,  0.        ,
        -0.23696   , -0.894962  , -0.7       ],
       [-0.647059  , -0.21608   , -0.180328  , -0.353535  , -0.791962  ,
        -0.0760059 , -0.854825  , -0.833333  ],
       [ 0.176471  ,  0.155779  ,  0.        ,  0.        ,  0.        ,
         0.052161  , -0.952178  , -0.733333  ],
       [-0.764706  ,  0.979899  

In [18]:
print(len(y_data)) 
y_data[:10]

759


array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [19]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in tqdm_notebook(range(10001)):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})       
        if step % 200 == 0 or step < 10 :
            print("Step : {} \t Cost : {}".format(step, cost_val))    

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
 
    

Step : 0 	 Cost : 1.2706477642059326
Step : 1 	 Cost : 1.2652075290679932
Step : 2 	 Cost : 1.2597957849502563
Step : 3 	 Cost : 1.2544119358062744
Step : 4 	 Cost : 1.2490564584732056
Step : 5 	 Cost : 1.2437294721603394
Step : 6 	 Cost : 1.2384308576583862
Step : 7 	 Cost : 1.2331607341766357
Step : 8 	 Cost : 1.227919101715088
Step : 9 	 Cost : 1.2227060794830322
Step : 200 	 Cost : 0.6815918684005737
Step : 400 	 Cost : 0.5800564289093018
Step : 600 	 Cost : 0.5586622953414917
Step : 800 	 Cost : 0.5490862131118774
Step : 1000 	 Cost : 0.5420495271682739
Step : 1200 	 Cost : 0.5360708236694336
Step : 1400 	 Cost : 0.5308253765106201
Step : 1600 	 Cost : 0.5261834263801575
Step : 1800 	 Cost : 0.5220587253570557
Step : 2000 	 Cost : 0.5183815360069275
Step : 2200 	 Cost : 0.515092670917511
Step : 2400 	 Cost : 0.5121421813964844
Step : 2600 	 Cost : 0.5094868540763855
Step : 2800 	 Cost : 0.5070899724960327
Step : 3000 	 Cost : 0.504919707775116
Step : 3200 	 Cost : 0.50294905900955

In [20]:
print("# Hypothesis: \n{h} \n\n# Correct (Y): \n{c} \n\n# Accuracy: {a}".format(
    # h = h, c = c, a = a
    h = h[:20], c = c[:20], a = a
))

# Hypothesis: 
[[0.4079657 ]
 [0.9303479 ]
 [0.22700569]
 [0.9483484 ]
 [0.29020914]
 [0.778755  ]
 [0.94921505]
 [0.6070346 ]
 [0.19412044]
 [0.558072  ]
 [0.70133424]
 [0.16109037]
 [0.39354497]
 [0.19378212]
 [0.79484665]
 [0.47803235]
 [0.7604104 ]
 [0.8610356 ]
 [0.8191446 ]
 [0.59507364]] 

# Correct (Y): 
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 

# Accuracy: 0.7747035622596741
