# NumPy Basics¶

In [13]:
from IPython.display import Image
from numpy.random import randn
import numpy as np

In [14]:
data = randn(2, 3)
data

array([[ 1.01865626,  0.80721223,  1.50314664],
       [-0.01719541,  0.150213  , -1.77840072]])

In [15]:
data * 10

array([[ 10.18656262,   8.07212225,  15.0314664 ],
       [ -0.17195405,   1.50213003, -17.78400721]])

In [17]:
data + data

array([[ 2.03731252,  1.61442445,  3.00629328],
       [-0.03439081,  0.30042601, -3.55680144]])

In [18]:
data

array([[ 1.01865626,  0.80721223,  1.50314664],
       [-0.01719541,  0.150213  , -1.77840072]])

In [19]:
data.shape

(2, 3)

In [20]:
data.dtype

dtype('float64')

### Creating ndarrays 

In [22]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [27]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
arr2.ndim

2

In [29]:
arr2.shape

(2, 4)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

In [33]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [35]:
np.arange(15)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays 

In [38]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [39]:
arr2 = np.array([1,2,3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [44]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [45]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [46]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [47]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

### Basic indexing and slicing 

In [49]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[5]

5

In [51]:
arr[5:8]

array([5, 6, 7])

In [52]:
arr[5:8] = 12

In [53]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [54]:
arr_slice = arr[5:8]

In [55]:
arr_slice

array([12, 12, 12])

In [56]:
arr_slice[1] = 1235
arr

array([   0,    1,    2,    3,    4,   12, 1235,   12,    8,    9])

In [57]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### 2차원 배열

In [60]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [61]:
arr2d[0][2]

3

In [62]:
arr2d[0, 2]

3

### 3차원 배열

In [63]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
old_value = arr3d[0].copy()
old_value

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
arr3d[0]= old_value
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d[1,0]

array([7, 8, 9])

### Indexing with slices 

In [69]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [70]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [72]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [75]:
arr2d[1, :2]

array([4, 5])

In [76]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

### Boolean indexing ¶

In [77]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [78]:
data = randn(7,4)
data

array([[-1.18059301, -0.42334179,  1.16412083,  1.42391697],
       [-0.24033816, -0.86627948,  2.18998472,  0.75617775],
       [-0.25595332,  0.93032204, -2.11518946, -1.36540412],
       [ 1.65463173,  0.2747502 , -0.34677614,  0.73845846],
       [ 0.85106768,  2.71993544, -0.47634162,  0.07307637],
       [-1.05817017, -0.23211018,  0.76031811,  1.96600929],
       [ 1.15943135, -0.55468245,  1.65769803, -0.2975753 ]])

In [79]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [80]:
data[names == 'Bob']

array([[-1.18059301, -0.42334179,  1.16412083,  1.42391697],
       [ 1.65463173,  0.2747502 , -0.34677614,  0.73845846]])

In [81]:
data[names == 'Bob', 2:]

array([[ 1.16412083,  1.42391697],
       [-0.34677614,  0.73845846]])

In [82]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [84]:
data[~(names == 'Bob')]

array([[-0.24033816, -0.86627948,  2.18998472,  0.75617775],
       [-0.25595332,  0.93032204, -2.11518946, -1.36540412],
       [ 0.85106768,  2.71993544, -0.47634162,  0.07307637],
       [-1.05817017, -0.23211018,  0.76031811,  1.96600929],
       [ 1.15943135, -0.55468245,  1.65769803, -0.2975753 ]])

### Fancy indexing 


In [85]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [86]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [89]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [90]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [92]:
arr[[4,5,7,2], [0,3,1,2]]

array([16, 23, 29, 10])

In [93]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [96]:
arr[np.ix_([1,5,7,2], [0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing arrays and swapping axes 

In [97]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [98]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [99]:
arr = np.random.randn(6,3)
arr

array([[-2.68069851,  0.04605795,  1.42471509],
       [-0.48585489, -0.10749479,  0.80839071],
       [-0.88533994, -1.47964398, -0.63418649],
       [-0.49664415, -0.54067392,  0.055145  ],
       [-0.59244519,  0.98532363,  0.12680307],
       [ 0.84130269, -1.37812978,  0.5629038 ]])

In [100]:
np.dot(arr.T, arr)

array([[ 9.51146318, -0.23590469, -3.2794604 ],
       [-0.23590469,  5.36545542,  0.236464  ],
       [-3.2794604 ,  0.236464  ,  3.4214818 ]])

In [103]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [104]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [105]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])